name: Create Test
on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  create_issue_stage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Get Branch diffs
        run: |
          git fetch

      - name: Get Branch diffs
        run: |
          echo "$(git log --oneline --no-merges --date=short origin/main...origin/develop)" >> test.txt
        id: diff_merges

      - name: cat
        run: |
          cat test.txt

      - name: read
        run: |
          readarray -t arr < test.txt
          for i in "${arr[@]}"
          do
            echo "- [] $i\n"
            echo "- [] $i\n" >> ISSUE.md
          done
        id: export_diff

      - name: cat
        run: |
          cat ISSUE.md

      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
        with:
          filename: ./ISSUE.md
          update_existing: true
          search_existing: all

      # - name: Get Branch diffs
      #   run: |
      #     echo "DIFF_MERGES2=testingfsfasdfsfdafds" >> $GITHUB_OUTPUT
      #   id: diff_merges2

      # - name: Use the value
      #   id: step_two
      #   run: |
      #     echo "diff_merges: ${{ steps.diff_merges.outputs.diff_merges }}"
      #     echo "diff_merges2: ${{ steps.diff_merges2.outputs.diff_merges2 }}"
      #     echo "---------------"
      #     echo "export_diff: ${{ steps.export_diff.outputs.export_diff }}"
