name: Create Test
on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  create_issue_stage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Get Branch diffs
        run: |
          git fetch

      - name: Get Branch diffs
        run: |
          echo 'BRANCH_DIFFERENCES<<EOF' >> $GITHUB_OUTPUT
          echo 'DIFF_MERGES=$(git log --oneline --no-merges --date=short origin/main...origin/develop)' >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_ENV
        id: diff_merges

      - name: Get Branch diffs
        run: |
          echo "DIFF_MERGES2=testing" >> $GITHUB_OUTPUT
        id: diff_merges2

      - name: Use the value
        id: step_two
        run: |
          echo "diff_merges: ${{ steps.diff_merges.outputs.diff_merges }}"
          echo "${{ steps.diff_merges.outputs.DIFF_MERGES }}"
          echo "other: ${{ steps.version.outputs.DIFF_MERGES }}"
          echo "env: ${{ env.DIFF_MERGES }}"
          echo "\n"
          echo "diff_merges: ${{ steps.diff_merges.outputs.diff_merges }}"
          echo "diff_merges2: ${{ steps.diff_merges2.outputs.diff_merges2 }}"
          echo "${{ steps.diff_merges2.outputs.DIFF_MERGES2 }}"
          echo "other: ${{ steps.version.outputs.DIFF_MERGES2 }}"
          echo "env: ${{ env.DIFF_MERGES2 }}"
